/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SceneStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
  'generating' : IDL.Null,
  'error' : IDL.Null,
});
export const Scene = IDL.Record({
  'id' : IDL.Text,
  'status' : SceneStatus,
  'order' : IDL.Nat,
  'replicateJobId' : IDL.Opt(IDL.Text),
  'projectId' : IDL.Text,
  'prompt' : IDL.Text,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ReplicateApiKey = IDL.Text;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScene' : IDL.Func([IDL.Text, IDL.Text], [Scene], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text], [Project], []),
  'createReplicatePrediction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'deleteScene' : IDL.Func([IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'getReplicateApiKey' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ReplicateApiKey)],
      [],
    ),
  'getScenesForProject' : IDL.Func([IDL.Text], [IDL.Vec(Scene)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'pollReplicatePrediction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'reorderScenes' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeReplicateApiKey' : IDL.Func([ReplicateApiKey], [], []),
  'transform' : IDL.Func([IDL.Record({ 'context' : IDL.Vec(IDL.Nat8), 'response' : IDL.Record({ 'status' : IDL.Nat, 'body' : IDL.Vec(IDL.Nat8), 'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })) }) })], [IDL.Record({ 'status' : IDL.Nat, 'body' : IDL.Vec(IDL.Nat8), 'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })) })], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SceneStatus = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
    'generating' : IDL.Null,
    'error' : IDL.Null,
  });
  const Scene = IDL.Record({
    'id' : IDL.Text,
    'status' : SceneStatus,
    'order' : IDL.Nat,
    'replicateJobId' : IDL.Opt(IDL.Text),
    'projectId' : IDL.Text,
    'prompt' : IDL.Text,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ReplicateApiKey = IDL.Text;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScene' : IDL.Func([IDL.Text, IDL.Text], [Scene], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text], [Project], []),
    'createReplicatePrediction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'deleteScene' : IDL.Func([IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'getReplicateApiKey' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ReplicateApiKey)],
        [],
      ),
    'getScenesForProject' : IDL.Func([IDL.Text], [IDL.Vec(Scene)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'pollReplicatePrediction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'reorderScenes' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeReplicateApiKey' : IDL.Func([ReplicateApiKey], [], []),
    'transform' : IDL.Func([IDL.Record({ 'context' : IDL.Vec(IDL.Nat8), 'response' : IDL.Record({ 'status' : IDL.Nat, 'body' : IDL.Vec(IDL.Nat8), 'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })) }) })], [IDL.Record({ 'status' : IDL.Nat, 'body' : IDL.Vec(IDL.Nat8), 'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })) })], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };